package ma.mpm.gov.automatiosationtool.model;

// Generated 2 sept. 2016 15:01:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name = "action", catalog = "project", uniqueConstraints = @UniqueConstraint(columnNames = "action"))
public class Action implements java.io.Serializable {

	private Integer idAction;
	private String action;
	private Set<Champ> champs = new HashSet<Champ>(0);

	public Action() {
	}

	public Action(String action) {
		this.action = action;
	}

	public Action(String action, Set<Champ> champs) {
		this.action = action;
		this.champs = champs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_action", unique = true, nullable = false)
	public Integer getIdAction() {
		return this.idAction;
	}

	public void setIdAction(Integer idAction) {
		this.idAction = idAction;
	}

	@Column(name = "action", unique = true, nullable = false, length = 25)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "action")
	public Set<Champ> getChamps() {
		return this.champs;
	}

	public void setChamps(Set<Champ> champs) {
		this.champs = champs;
	}

}
