package ma.mpm.gov.automatiosationtool.model;

// Generated 2 sept. 2016 15:01:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etape generated by hbm2java
 */
@Entity
@Table(name = "etape", catalog = "project")
public class Etape implements java.io.Serializable {

	private Integer numEtape;
	private Module module;
	private String nomEtape;
	private Set<Menu> menus = new HashSet<Menu>(0);
	private Set<Champ> champs = new HashSet<Champ>(0);
	private Set<TestEtape> testEtapes = new HashSet<TestEtape>(0);

	public Etape() {
	}

	public Etape(Module module, String nomEtape, Set<Menu> menus,
			Set<Champ> champs, Set<TestEtape> testEtapes) {
		this.module = module;
		this.nomEtape = nomEtape;
		this.menus = menus;
		this.champs = champs;
		this.testEtapes = testEtapes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "num_etape", unique = true, nullable = false)
	public Integer getNumEtape() {
		return this.numEtape;
	}

	public void setNumEtape(Integer numEtape) {
		this.numEtape = numEtape;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_module")
	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	@Column(name = "nom_etape", length = 25)
	public String getNomEtape() {
		return this.nomEtape;
	}

	public void setNomEtape(String nomEtape) {
		this.nomEtape = nomEtape;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etape")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etape")
	public Set<Champ> getChamps() {
		return this.champs;
	}

	public void setChamps(Set<Champ> champs) {
		this.champs = champs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etape")
	public Set<TestEtape> getTestEtapes() {
		return this.testEtapes;
	}

	public void setTestEtapes(Set<TestEtape> testEtapes) {
		this.testEtapes = testEtapes;
	}

}
