package ma.mpm.gov.automatiosationtool.model;

// Generated 2 sept. 2016 15:01:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "project", uniqueConstraints = @UniqueConstraint(columnNames = "nom_menu"))
public class Menu implements java.io.Serializable {

	private Integer idMenu;
	private Etape etape;
	private String nomMenu;
	private Set<Champ> champs = new HashSet<Champ>(0);

	public Menu() {
	}

	public Menu(String nomMenu) {
		this.nomMenu = nomMenu;
	}

	public Menu(Etape etape, String nomMenu, Set<Champ> champs) {
		this.etape = etape;
		this.nomMenu = nomMenu;
		this.champs = champs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_menu", unique = true, nullable = false)
	public Integer getIdMenu() {
		return this.idMenu;
	}

	public void setIdMenu(Integer idMenu) {
		this.idMenu = idMenu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "num_etape")
	public Etape getEtape() {
		return this.etape;
	}

	public void setEtape(Etape etape) {
		this.etape = etape;
	}

	@Column(name = "nom_menu", unique = true, nullable = false, length = 25)
	public String getNomMenu() {
		return this.nomMenu;
	}

	public void setNomMenu(String nomMenu) {
		this.nomMenu = nomMenu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<Champ> getChamps() {
		return this.champs;
	}

	public void setChamps(Set<Champ> champs) {
		this.champs = champs;
	}

}
