package ma.mpm.gov.automatiosationtool.model;

// Generated 2 sept. 2016 15:01:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = "project", uniqueConstraints = @UniqueConstraint(columnNames = "nom_module"))
public class Module implements java.io.Serializable {

	private Integer idModule;
	private String nomModule;
	private Set<Etape> etapes = new HashSet<Etape>(0);

	public Module() {
	}

	public Module(String nomModule) {
		this.nomModule = nomModule;
	}

	public Module(String nomModule, Set<Etape> etapes) {
		this.nomModule = nomModule;
		this.etapes = etapes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_module", unique = true, nullable = false)
	public Integer getIdModule() {
		return this.idModule;
	}

	public void setIdModule(Integer idModule) {
		this.idModule = idModule;
	}

	@Column(name = "nom_module", unique = true, nullable = false, length = 25)
	public String getNomModule() {
		return this.nomModule;
	}

	public void setNomModule(String nomModule) {
		this.nomModule = nomModule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Etape> getEtapes() {
		return this.etapes;
	}

	public void setEtapes(Set<Etape> etapes) {
		this.etapes = etapes;
	}

}
