package ma.mpm.gov.automatiosationtool.model;

// Generated 2 sept. 2016 15:01:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Selecteur generated by hbm2java
 */
@Entity
@Table(name = "selecteur", catalog = "project", uniqueConstraints = @UniqueConstraint(columnNames = "type_selecteur"))
public class Selecteur implements java.io.Serializable {

	private Integer idSelecteur;
	private String typeSelecteur;
	private Set<Champ> champs = new HashSet<Champ>(0);

	public Selecteur() {
	}

	public Selecteur(String typeSelecteur) {
		this.typeSelecteur = typeSelecteur;
	}

	public Selecteur(String typeSelecteur, Set<Champ> champs) {
		this.typeSelecteur = typeSelecteur;
		this.champs = champs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_selecteur", unique = true, nullable = false)
	public Integer getIdSelecteur() {
		return this.idSelecteur;
	}

	public void setIdSelecteur(Integer idSelecteur) {
		this.idSelecteur = idSelecteur;
	}

	@Column(name = "type_selecteur", unique = true, nullable = false, length = 25)
	public String getTypeSelecteur() {
		return this.typeSelecteur;
	}

	public void setTypeSelecteur(String typeSelecteur) {
		this.typeSelecteur = typeSelecteur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "selecteur")
	public Set<Champ> getChamps() {
		return this.champs;
	}

	public void setChamps(Set<Champ> champs) {
		this.champs = champs;
	}

}
