package ma.mpm.gov.automatiosationtool.model;

// Generated 2 sept. 2016 15:01:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test", catalog = "project")
public class Test implements java.io.Serializable {

	private Integer idTest;
	private String description;
	private Date dateTest;
	private Set<TestEtape> testEtapes = new HashSet<TestEtape>(0);

	public Test() {
	}

	public Test(String description, Date dateTest, Set<TestEtape> testEtapes) {
		this.description = description;
		this.dateTest = dateTest;
		this.testEtapes = testEtapes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_test", unique = true, nullable = false)
	public Integer getIdTest() {
		return this.idTest;
	}

	public void setIdTest(Integer idTest) {
		this.idTest = idTest;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_test", length = 10)
	public Date getDateTest() {
		return this.dateTest;
	}

	public void setDateTest(Date dateTest) {
		this.dateTest = dateTest;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "test")
	public Set<TestEtape> getTestEtapes() {
		return this.testEtapes;
	}

	public void setTestEtapes(Set<TestEtape> testEtapes) {
		this.testEtapes = testEtapes;
	}

}
