package ma.mpm.gov.automatiosationtool.model;

// Generated 2 sept. 2016 15:01:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestEtape generated by hbm2java
 */
@Entity
@Table(name = "test_etape", catalog = "project")
public class TestEtape implements java.io.Serializable {

	private TestEtapeId id;
	private Test test;
	private Etape etape;
	private Boolean resultat;

	public TestEtape() {
	}

	public TestEtape(TestEtapeId id, Test test, Etape etape) {
		this.id = id;
		this.test = test;
		this.etape = etape;
	}

	public TestEtape(TestEtapeId id, Test test, Etape etape, Boolean resultat) {
		this.id = id;
		this.test = test;
		this.etape = etape;
		this.resultat = resultat;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idTest", column = @Column(name = "id_test", nullable = false)),
			@AttributeOverride(name = "numEtape", column = @Column(name = "num_etape", nullable = false)) })
	public TestEtapeId getId() {
		return this.id;
	}

	public void setId(TestEtapeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_test", nullable = false, insertable = false, updatable = false)
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "num_etape", nullable = false, insertable = false, updatable = false)
	public Etape getEtape() {
		return this.etape;
	}

	public void setEtape(Etape etape) {
		this.etape = etape;
	}

	@Column(name = "resultat")
	public Boolean getResultat() {
		return this.resultat;
	}

	public void setResultat(Boolean resultat) {
		this.resultat = resultat;
	}

}
