package ma.mpm.gov.automatiosationtool.model;

// Generated 2 sept. 2016 15:01:40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TestEtapeId generated by hbm2java
 */
@Embeddable
public class TestEtapeId implements java.io.Serializable {

	private int idTest;
	private int numEtape;

	public TestEtapeId() {
	}

	public TestEtapeId(int idTest, int numEtape) {
		this.idTest = idTest;
		this.numEtape = numEtape;
	}

	@Column(name = "id_test", nullable = false)
	public int getIdTest() {
		return this.idTest;
	}

	public void setIdTest(int idTest) {
		this.idTest = idTest;
	}

	@Column(name = "num_etape", nullable = false)
	public int getNumEtape() {
		return this.numEtape;
	}

	public void setNumEtape(int numEtape) {
		this.numEtape = numEtape;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestEtapeId))
			return false;
		TestEtapeId castOther = (TestEtapeId) other;

		return (this.getIdTest() == castOther.getIdTest())
				&& (this.getNumEtape() == castOther.getNumEtape());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTest();
		result = 37 * result + this.getNumEtape();
		return result;
	}

}
