package ma.mpm.gov.automatiosationtool.model;

// Generated 2 sept. 2016 15:01:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TypeChamp generated by hbm2java
 */
@Entity
@Table(name = "type_champ", catalog = "project", uniqueConstraints = @UniqueConstraint(columnNames = "nom_type"))
public class TypeChamp implements java.io.Serializable {

	private Integer idType;
	private String nomType;
	private Set<Champ> champs = new HashSet<Champ>(0);

	public TypeChamp() {
	}

	public TypeChamp(String nomType, Set<Champ> champs) {
		this.nomType = nomType;
		this.champs = champs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_type", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "nom_type", unique = true, length = 25)
	public String getNomType() {
		return this.nomType;
	}

	public void setNomType(String nomType) {
		this.nomType = nomType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeChamp")
	public Set<Champ> getChamps() {
		return this.champs;
	}

	public void setChamps(Set<Champ> champs) {
		this.champs = champs;
	}

}
